### ISSUE TITLE
file-mime-type or enclosure-mime-type?

### ISSUE THREAD

**Issue by ghost** [podlove/podlove-specifications#11]
from the example:
 `<file-mime-type>audio/mpeg</enclosure-mime-type>`

I assume file-mime-type is correct. Isn't it?

**Comment by ghost** [comment]
Also the episodes example ends with `</podcast>` and `<file-title>` ends with `</feed-title>`  (cut'n'paste :D)

**Comment by timpritlove** [comment]
Thanks. Fixed.
