### ISSUE TITLE
Deprecate hash notation in deep-link URLs

### ISSUE THREAD

**Issue by mahemoff** [podlove/podlove-specifications#17]
I'd like to propose deprecating the hash prefix for Podlove URLs and require just the convention `?`-prefixed CGI param style. I believe hash should be deprecated for the following reasons:
- It's unnecessary and effectively deprecated on the web in general - Hash and hashbang were hacks for client-side state changes until HTML5 history came along. It's now well-established (http://caniuse.com/#feat=history), meaning that clients can directly add and change `?`-prefixed URL params.
- Web browsers don't upload hash parameters to web servers (by design). This makes it hard to centralise parsing logic in the server; either the logic has to be duplicated in client and server, or the client has to pass it to the server, which adds complexity and slows down the initial experience.
- It adds some general parsing and formatting complexity.

**Comment by timpritlove** [comment]
Look at the spec - we actually do not mandate the has sign at all. It's up to the website owner to specify the hash in the base URL. So you could come up with URLs that just end in "?" too.

**Comment by mahemoff** [comment]
The spec seems to imply it (https://github.com/podlove/podlove-specifications/blob/master/podlove-deep-linking.md#additional-fragment-parameters) but I guess it's endorsed by Media Fragments standard, so not much can be done about it, though that standard makes it difficult to centralise logic due to # arguments not being passed to server.
