### ISSUE TITLE
Cover nach Bilderwechsel auf Wordpress weg

### ISSUE THREAD

**Issue by dnlmb** [podlove/podlove-specifications#21]
Nach dem ich auf Worfpress unser Cover neu hochgeladen habe, wird im Podlove Player, im Widget und auch über den Feed kein Bild mehr übertragen. 

Cache leeren und reparieren hilft Nicht. Dabei gibt es ganz viele Fehler. 

https://coffeeandchainrings.de

**Comment by saerdnaer** [comment]
Ich glaube da ist du hier im falschen Repo, Support gibts auf https://sendegate.de/ oder https://community.podlove.org/
